Description: Deploys a single webserver instance

Resources:
  webServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-7c87d913
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref securityGroup
  securityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: access web application
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80

